name: foxy build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.11.0
      - name: setup ROS2
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: foxy
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: foxy
          skip-tests: true
