name: ROS2 build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - foxy
          - humble
          - rolling
        include:
          - docker_image: ubuntu:focal
            ros_distribution: foxy
          - docker_image: ubuntu:jammy
            ros_distribution: humble
          - docker_image: ubuntu:jammy
            ros_distribution: rolling
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.11.0
      - name: setup ROS2
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true

